"""Add class timing to QR codes

Revision ID: 99907490a460
Revises: 
Create Date: 2025-08-06 23:21:31.345539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99907490a460'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('class_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.drop_column('class_end_time')
        batch_op.drop_column('class_start_time')

    # ### end Alembic commands ###
